apiVersion: v1
kind: Service
metadata:
  name: autoscaler-operator
  labels:
    app: autoscaler-operator
spec:
  selector:
    app: autoscaler-operator
  # for future integration - custom REST API triggers...
  ports:
    - name: http
      protocol: TCP
      port: 8432
      targetPort: 18432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-operator
spec:
  selector:
    matchLabels:
      app: autoscaler-operator
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: autoscaler-operator
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: experiment-logs-storage
          persistentVolumeClaim:
            claimName: experiment-logs-pvc
        - name: autoscaler-operator-config
          configMap:
            name: autoscaler-operator-config
            items:
              - key: auto_scaler_conf
                path: auto_scaler_conf.yaml
        - name: kube-config
          configMap:
            name: kube-config
      containers:
        - name: autoscaler-operator
          image: leonidusername5432/kubescale-controller:0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2000Mi"
              cpu: "5000m"
            requests:
              memory: "1000Mi"
              cpu: "600m"
          volumeMounts:
            - name: autoscaler-operator-config
              mountPath: /conf/autoscaler-operator
            - name: kube-config
              mountPath: /conf/kube/config
              subPath: config
            - name: experiment-logs-storage # Должно совпадать с именем тома в 'volumes'
              mountPath: /experiment_logs   # Путь внутри контейнера, куда монтировать том
          ports:
            - name: http
              protocol: TCP
              containerPort: 9301
          args:
            - python
            - /src/controller.py
          env:
            - name: KUBECONFIG
              value: /conf/kube/config
            - name: AUTOSCALER_CONFIG_FILE
              value: /conf/autoscaler-operator/auto_scaler_conf.yaml
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password
      nodeSelector:
        nodetype: main
      restartPolicy: Always
