apiVersion: v1
kind: Secret
metadata:
  name: email-secret # Имя, используемое в setup.sh
  # Укажите namespace, если он отличен от default и известен,
  # иначе он будет применен к namespace, указанному при запуске setup.sh
  # namespace: ваш-namespace
type: Opaque
data:
  # Ключ для имени пользователя. Замените ЗАКОДИРОВАННЫЙ_ЛОГИН
  # на результат команды 'echo -n 'ВАШ_EMAIL_ЛОГИН' | base64'
  username: =

  # Ключ для пароля. Замените ЗАКОДИРОВАННЫЙ_ПАРОЛЬ
  # на результат команды 'echo -n 'ВАШ_ПАРОЛЬ_ИЛИ_API_КЛЮЧ' | base64'
  password: /
