apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:latest
        ports:
        - containerPort: 9113
        args:
        - -nginx.scrape-uri=http://simple-app:80/stub_status
        resources:
          requests:
            memory: "64Mi"  # Запрашиваемая память
            cpu: "250m"     # Запрашиваемый CPU
          limits:
            memory: "128Mi" # Максимально допустимая память
            cpu: "500m"     # Максимально допустимый CPU
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
spec:
  ports:
  - port: 9113
    targetPort: 9113
  selector:
    app: nginx-prometheus-exporter
