apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: simple-app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.default.svc.cluster.local:9090
      metricName: promhttp_metric_handler_requests_total
      query: promhttp_metric_handler_requests_total
      threshold: "5"
