apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-access
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
