{{- if .Values.keda.enabled }}
{{- range .Values.keda.scaledObjects }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .scaleTargetRef.kind }}
    name: {{ .scaleTargetRef.name }}
  minReplicaCount: {{ .minReplicaCount }}
  maxReplicaCount: {{ .maxReplicaCount }}
  {{- if .pollingInterval }}
  pollingInterval: {{ .pollingInterval }}
  {{- end }}
  triggers:
  {{- toYaml .triggers | nindent 4 }}
{{- end }}
{{- end }} 
