{{- if .Values.nginxExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mychart.fullname" . }}-exporter
  template:
    metadata:
      labels:
        app: {{ include "mychart.fullname" . }}-exporter
    spec:
      containers:
      - name: exporter
        image: {{ .Values.nginxExporter.image }}
        ports:
        - containerPort: 9113
        args:
        - -nginx.scrape-uri=http://{{ .Values.nginx.serviceName }}:{{ .Values.nginx.servicePort }}/stub_status
        resources: {{ .Values.nginxExporter.resources | toYaml | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-exporter
spec:
  ports:
  - port: 9113
    targetPort: 9113
  selector:
    app: {{ include "mychart.fullname" . }}-exporter
{{- end }} 
