apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
  labels:
    app: cadvisor
spec:
  hostNetwork: true
  containers:
    - name: cadvisor
      image: gcr.io/cadvisor/cadvisor:v0.47.2
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
  volumes:
    - name: rootfs
      hostPath:
        path: /
    - name: sys
      hostPath:
        path: /sys
    - name: docker
      hostPath:
        path: /var/lib/docker
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: default
spec:
  selector:
    app: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
