apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-single
spec:
  selector:
    matchLabels:
      app: victoria-metrics-single
  replicas: 1
  template:
    metadata:
      labels:
        app: victoria-metrics-single
    spec:
      containers:
      - name: victoria-metrics
        image: victoriametrics/victoria-metrics:v1.99.0 #  Используйте актуальную версию
        ports:
        - containerPort: 8428 #  Порт для приема и запросов
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-single
spec:
  type: NodePort  
  selector:
    app: victoria-metrics-single
  ports:
  - protocol: TCP
    port: 8428        # Порт, на который будет доступен сервис
    targetPort: 8428  # Порт, на который будет направлен трафик в контейнер
    nodePort: 30000   # Укажите желаемый порт в диапазоне 30000-32767
