remoteWrite:
  - url: http://victoria-metrics-single:8428/api/v1/write

scrapeConfigs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.monitoring.svc:8080']

  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        regex: node-exporter
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: metrics
        action: keep
