remoteWrite:
  - url: http://victoria-metrics-single:8428/api/v1/write

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.monitoring.svc:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter-prometheus-node-exporter.default.svc.cluster.local:9100']

