apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-prometheus-exporter:9113']
      # - job_name: 'cadvisor'
      #   static_configs:
      #   - targets: ['cadvisor.default.svc:8080']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc:8080']
