apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL2RlbW86ZGVtb0AxOTIuMTY4LjEuNTc6NTY3Mi92aG9zdA== # echo -n amqp://demo:demo@192.168.1.57:5672/vhost | base64
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret # Имя нашего секрета
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
spec:
  scaleTargetRef:
    name: nginx-deployment # Имя nginx-деплоймента который хотим масштабировать
  minReplicaCount: 1       # Меньше одной реплики не хотим
  maxReplicaCount: 5       # А то же время больше пяти тоже
  pollingInterval: 10      # Как часто ходить за метрикой
  cooldownPeriod:  10     # Сколько времени ждать для даунскейла
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: demo_queue # Наша демо-очередь
      mode: QueueLength
      value: "3" # Если в очереди три новых сообщения — добавляем под
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
