{
 "title": "FinalThesis-Spiky,CPU,pythonwebapp2-avg",
 "time": { "from": "2020-08-26T08:30:00.000Z", "to": "2020-08-26T09:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "webapp_name",
    "query": "pythonwebapp,pythonwebapp,pythonwebapp2"
   }
  ]
 },
 "panels": [
  {
   "title": "Application without auto-scaling",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 0 },
   "options": { "content": "  " }
  },
  { "title": "Kubernetes HPA", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 5, "y": 0 }, "options": { "content": "  " } },
  { "title": "Reactive auto-scaler", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 10, "y": 0 }, "options": { "content": "  " } },
  {
   "title": "IntelliScaler proactive auto-scaler",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 15, "y": 0 },
   "options": { "content": "  " }
  },
  {
   "title": "1(a)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m])) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m)) ) / 6",
     "legendFormat": " Requests per second (left)"
    },
    {
     "expr": "(count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m))) / 6",
     "legendFormat": "Number of running pods (right)"
    }
   ]
  },
  {
   "title": "2(a)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m])) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m)) ) / 6",
     "legendFormat": " Requests per second (left)"
    },
    {
     "expr": "(count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m))) / 6",
     "legendFormat": "Number of running pods (right)"
    }
   ]
  },
  {
   "title": "3(a)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m])) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m)) ) / 6",
     "legendFormat": " Requests per second (left)"
    },
    {
     "expr": "(count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m))) / 6",
     "legendFormat": "Number of running pods (right)"
    }
   ]
  },
  {
   "title": "4(a)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m])) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) + sum(rate(envoy_cluster_upstream_rq{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m)) ) / 6",
     "legendFormat": " Requests per second (left)"
    },
    {
     "expr": "(count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)) +count(count by (pod) (eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]].*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m))) / 6",
     "legendFormat": "Number of running pods (right)"
    }
   ]
  },
  {
   "title": "1(b)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale", "label": "95th %tile response time (ms)" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m])) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m))) / 6",
     "legendFormat": "95th percentile response time (ms)"
    }
   ]
  },
  {
   "title": "2(b)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "95th %tile response time (ms)" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m])) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m))) / 6",
     "legendFormat": "95th percentile response time (ms)"
    }
   ]
  },
  {
   "title": "3(b)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "95th %tile response time (ms)" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m])) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m))) / 6",
     "legendFormat": "95th percentile response time (ms)"
    }
   ]
  },
  {
   "title": "4(b)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "95th %tile response time (ms)" }
   ],
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m])) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 30m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 60m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 90m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 120m)) +histogram_quantile(0.95, rate( envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$webapp_name\"}[1m] offset 150m))) / 6",
     "legendFormat": "95th percentile response time (ms)"
    }
   ]
  },
  {
   "title": "1(c)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "Avg. pod CPU usage (%)" }
   ],
   "targets": [
    {
     "expr": "(sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"}) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 30m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 60m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 90m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 120m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 150m))/6",
     "legendFormat": "Avg. pod CPU usage(%)"
    }
   ]
  },
  {
   "title": "2(c)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "Avg. pod CPU usage (%)" }
   ],
   "targets": [
    {
     "expr": "(sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"}) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 30m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 60m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 90m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 120m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 150m))/6",
     "legendFormat": "Average pod CPU usage (%)"
    }
   ]
  },
  {
   "title": "3(c)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "Avg. pod CPU usage (%)" }
   ],
   "targets": [
    {
     "expr": "(sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"}) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 30m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 60m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 90m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 120m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 150m))/6",
     "legendFormat": " Average pod CPU usage (%)"
    }
   ]
  },
  {
   "title": "4(c)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "percentunit", "label": "Avg. pod CPU usage (%)" }
   ],
   "targets": [
    {
     "expr": "(sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" })/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"}) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 30m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 30m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 60m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 60m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 90m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 90m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 120m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 120m) +sum(eagle_pod_container_resource_usage_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\" } offset 150m)/ sum(eagle_pod_container_resource_requests_cpu_cores{ pod=~\"[[webapp_name]]-.*\", container!=\"POD\", container=~\"[[webapp_name]]\", phase=\"Running\"} offset 150m))/6",
     "legendFormat": " Average pod CPU usage (%)"
    }
   ]
  }
 ]
}