{
 "title": "Dashboard for experiment",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Application requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(http_server_requests_seconds_count{instance=~\".*.pythonwebapp.default.svc.cluster.local:9100\", uri=\"/bmark/request/{id}\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(sum by (instance,cpu) (irate(node_cpu_seconds_total{mode='user', instance!='193.61.36.48:9100'}[5m])))\n"
    }
   ]
  },
  {
   "title": "Network usage (total)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_network_receive_bytes_total{instance!='193.61.36.48:9100'}[5m])) + sum by (instance)(irate(node_network_transmit_bytes_total{instance!='193.61.36.48:9100'}[5m]))"
    }
   ]
  },
  {
   "title": "Disk usage (total)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{instance!='193.61.36.48:9100',device=~\"[a-z]*[a-z]\"}[5m]) + irate(node_disk_written_bytes_total{instance!='193.61.36.48:9100',device=~\"[a-z]*[a-z]\"}[5m]))"
    }
   ]
  }
 ]
}